## \u670D\u52A1\u914D\u7F6E
server:
  # SpringBoot\u670D\u52A1\u7AEF\u53E3\u914D\u7F6E
  port: 8000
  # SpringBoot\u8BBE\u7F6E\u54CD\u5E94\u538B\u7F29gzip
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,text/css,application/json,application/gltf,application/xml,text/html,text/xml,text/plain
  servlet:
    # \u5E94\u7528\u7684\u8BBF\u95EE\u8DEF\u5F84
    context-path: /
  tomcat:
    uri-encoding: UTF-8 # tomcat\u7684URI\u7F16\u7801
    threads:
      max: 300
      min-spare: 30


## Spring
spring:
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet.content-type: text/html
    cache: false

  # postgresql
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.17.30.255:5432/land_house_dev
      username: postgres
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      #      validation-query: select '1' from public
      test-while-idle: true

      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall